### ISSUE TITLE
如何将scroller中的Data，Data传递给cell？

### ISSUE THREAD

**Issue by dyguests** [Brian-Jiang/UnlimitedScrollUI#18]
你好，非常棒的工具！

想请教一个问题：
对于scroller中的list<Data>，怎么将Data传递给cell?

**Comment by dyguests** [comment]
我目录的一个方案是：

![image](https://user-images.githubusercontent.com/7933189/169653272-5034a0c9-2aa4-4636-bb7e-df5febcbe795.png)

![image](https://user-images.githubusercontent.com/7933189/169653326-d3af56bf-7215-4a92-b6a3-a03213dbf106.png)

![image](https://user-images.githubusercontent.com/7933189/169653305-20ae57e2-7fb8-4fac-a8b3-5ae257b135f8.png)

不知道有没有更好的办法。

**Comment by Brian-Jiang** [comment]
这样应该是可以的，本来想的是在OnGenerated里去对应的地方拿data，不过确实把data直接传过来有时候会更好，之后在package里也补充一下👍

**Comment by dyguests** [comment]
我目前的方案有点丑
我用了好几个scroller，都没看到一种好的初始化 item 数据的方式。

从架构设计上来说，在 scroller 中对 cell 进行设值是一个好的办法。

感觉用
scroller.Generate(prefab,count, onBind=(cell, index)=>{ ... });
会不会好点。

**Comment by Brian-Jiang** [comment]
#20
