### ISSUE TITLE
ICell.OnGenerated不仅处理初始化逻辑，还处理复用逻辑？

### ISSUE THREAD

**Issue by dyguests** [Brian-Jiang/UnlimitedScrollUI#19]
因为Cell可以复用，对于数据绑定都在ICell.OnGenerated时发生。

能否将 OnGenerate 分为
OnCreate
OnBind
两个阶段（此处方法命名只是参考于Android）

这样所有 cell 一致的数据初始化处理放在 OnCreate
不一致的数据放在 OnBind 中

**Comment by Brian-Jiang** [comment]
#20
