### ISSUE TITLE
【脚本缺失】Ver.1.5.0 ？

### ISSUE THREAD

**Issue by dyguests** [Brian-Jiang/UnlimitedScrollUI#22]
![image](https://user-images.githubusercontent.com/7933189/173237703-e69b36f8-0dcf-404e-b2a3-8aa6bed15843.png)

我更新到1.5.0后，抛了空指针。

然后我尝试看一下Demo是怎么处理的，发现Demo有点问题，如图。

我新建了一个新的项目，导入 1.5.0。此问题仍存在。

**Comment by dyguests** [comment]
其中的空指针问题解决了。（Demo的脚本缺失还在）
是因为脚本缺失导致我的Prefab的component ICell 找不到了。

![image](https://user-images.githubusercontent.com/7933189/173238041-2e9122c0-7c47-4769-8520-b1cdff63ae4c.png)
导致在Generate时，取不到ICell，返回空指针。

【建议】
因为没有对List item 做 类型检查，能否在
UnlimitedScrollUI.VerticalUnlimitedScroller.GenerateCell
中
iCell = instance.GetComponent<ICell>();
后，如果iCell为空时，明示下iCell 为空？
添加个
if null then throw InvalidCastException
啥的。

**Comment by dyguests** [comment]
另：
UnlimitedScrollUI.RegularCell.onGenerated
这个方法应该可以删除了哇。

**Comment by Brian-Jiang** [comment]
> ![image](https://user-images.githubusercontent.com/7933189/173237703-e69b36f8-0dcf-404e-b2a3-8aa6bed15843.png)
> 
> 我更新到1.5.0后，抛了空指针。
> 
> 然后我尝试看一下Demo是怎么处理的，发现Demo有点问题，如图。
> 
> 我新建了一个新的项目，导入 1.5.0。此问题仍存在。

看了下应该是我在传asset store版的时候没仔细检查😅package里的demo是没问题的
我重新传一下

**Comment by Brian-Jiang** [comment]
另外那个判断确实可以加一下👍
